### PR TITLE
Added condition for check based on set time

### PR DESCRIPTION
**Pull request by kerkenit**
So I can trigger when the sunset is after 21:45 so I know its summer.
(For chill summer music)
schermafbeelding 2017-05-16 om 19 41 06

### CODE REVIEW

**Comment by kerkenit** [comment]
I tried to make a new pull request for the app title, but its auto joined with this one:
schermafbeelding 2017-05-16 om 19 59 23

**Comment by magtimmermans** [comment]
Please test everything carefully.

**Comment by kerkenit** [comment]
I did. Is there a problem? Here it's working fine

**Comment by magtimmermans** [comment]
Hi, Sorry for late reply. I haven't much time yet. I thought but the bug is also in the current live version. I am not sure if it is even a bug or only not nice displayed.

Invalid date	Einde Nacht
Invalid date	Nacht begint

**Pull request merged**
